FROM alpine/java:11.0.24

WORKDIR /app
RUN chmod 777 .

RUN apk update && apk add --no-cache bash && apk add curl
COPY udpserver/build/libs/udpserver.jar udpserver.jar
COPY udpclient/build/libs/udpclient.jar udpclient.jar

# ENTRYPOINT ["java", "-jar", "udpserver.jar", "0.0.0.0", "12345"]
CMD /bin/bash
